#!/data/data/com.termux/files/usr/bin/bash

cd ~/

if [ -d ~/gpac ]; then
	echo removing old 'gpac' dir
	rm -rf ~/gpac
fi


git clone https://github.com/manishwg/gpac.git
cd gpac
chmod 775 ./configure
chmod 775 ./check_revision.sh
./configure --static-mp4box --use-zlib=no
make -j4