#!/data/data/com.termux/files/usr/bin/bash


assert_not_root() {
	if [ $(id -u) -eq 0 ]
	then
		echo "This must NOT be run as root as it will break your environment (root will be required for nearly everything due to changed file permissions)"
		exit 1
	fi
}
assert_not_root
termux-wake-lock

echo -e "\n #### Setting '.bashrc' and  'bash_aliases'"
if [ -e ~/.bashrc ]; then
	echo removing old '.bashrc'
	rm -rf ~/.bashrc
fi

if [ -e ~/.bash_aliases ]; then
	echo removing old '.bash_aliases'
	rm -rf ~/.bash_aliases
fi

ln -sv ~/termux-env/.bashrc ~/
ln -sv ~/termux-env/.bash_aliases ~/

source ~/.bashrc



echo -e "\n #### upgrading installed packages..."
apt update
apt full-upgrade -y

echo -e "\n"

# Base pkg
echo -e "\n #### installing python python-dev..."
apt install -y python python-dev
echo -e "\n #### installing clang n make..."
apt install -y clang make
echo -e "\n #### installing ncurses-utils..."
apt install -y ncurses-utils # sudo dependancy
echo -e "\n #### upgrading pip..."
pip install --upgrade pip
echo -e "\n"

# ytdl
echo -e "\n #### installing youtube-dl..."
pip install --upgrade youtube-dl
echo -e "\n #### installing ffmpeg n atomicparsley..."
apt install -y ffmpeg atomicparsley
echo -e "\n"

# saavn
echo -e "\n #### installing pip lxml dependencies..."
apt install -y libxml2 libxml2-dev libxslt libxslt-dev
echo -e "\n #### installing pip module 'lxml'..."
pip install --upgrade lxml
echo -e "\n #### installing pip module 'requests'..."
pip install --upgrade requests
echo -e "\n #### installing pip module 'mutagen'..."
pip install --upgrade mutagen
echo -e "\n"
 



if [ -f ~/termux-env/mp4box/$(uname -m) ]; then
	echo -e "\n #### Linking prebuid mp4box..."
	ln -sv ~/termux-env/mp4box/$(uname -m) ~/termux-env/bin/mp4box
else
	echo -e "\n #### No prebuid mp4box, trying to build..."
	cwd2=$(pwd)
	cd ~/
	git clone https://github.com/manishwg/gpac.git
	cd gpac
	chmod 775 ./configure
	chmod 775 ./check_revision.sh
	./configure --static-mp4box --use-zlib=no
	make -j4
	cd $cwd2
	if [ -f ~/gpac/bin/gcc/MP4Box ]; then
		echo -e "\n #### Build OK, Linking mp4box..."
		mv -f ~/gpac/bin/gcc/MP4Box ~/termux-env/mp4box/$(uname -m)
		ln -sv ~/termux-env/mp4box/$(uname -m) ~/termux-env/bin/mp4box
	fi

fi

devicemodel=$(getprop ro.product.model)
devicemodel=$(echo $devicemodel | sed -e "s: ::g")
# echo $devicemodel
if [ -e ~/termux-env/patches/$devicemodel ]; then
	echo -e "\n #### patching ~/termux-env/patches/$devicemodel"
	bash ~/termux-env/patches/$devicemodel
else
	echo -e "\n #### no patches Linking bins"
	ln -sv ~/termux-env/topatch/bin/* ~/termux-env/bin/
fi



echo -e "\n #### Setting ~/bin"

chmod 774 ~/termux-env/bin
chmod 775 ~/termux-env/bin/*

if [[ -L ~/bin && -d ~/bin ]]
then
	echo removing previous '~/bin'
	rm -rf ~/bin
fi

cwd2=$(pwd)
cd ~
ln -sv ./termux-env/bin ~/
cd $cwd2

termux-wake-unlock