#!/data/data/com.termux/files/usr/bin/bash

if [ -e ~/.bashrc ]; then
	echo removing old '.bashrc'
	rm -rf ~/.bashrc
fi

if [ -e ~/.bash_aliases ]; then
	echo removing old '.bash_aliases'
	rm -rf ~/.bash_aliases
fi

ln -sv ~/termux-env/.bashrc ~/
ln -sv ~/termux-env/.bash_aliases ~/




echo -e "\n #### upgrading installed packages..."
pkg upgrade

# Base pkg
echo -e "\n #### installing python python-dev...\n"
apt install -y python python-dev
echo -e "\n #### installing clang...\n"
apt install -y clang
echo -e "\n #### installing ncurses-utils...\n"
apt install -y ncurses-utils # sudo dependancy
echo -e "\n"
pip install --upgrade pip
echo -e "\n"

# ytdl
pip install --upgrade youtube-dl
echo -e "\n"
apt install -y ffmpeg
echo -e "\n"
apt install -y atomicparsley
echo -e "\n"

# saavn
apt install -y libxml2 libxml2-dev 
echo -e "\n"
apt install -y libxslt libxslt-dev
echo -e "\n"
pip install --upgrade lxml
echo -e "\n"
pip install --upgrade requests
echo -e "\n"
pip install --upgrade mutagen
echo -e "\n"
 



if [ -f ~/termux-env/mp4box/$(uname -m) ]; then
	ln -sv ~/termux-env/mp4box/$(uname -m) ~/termux-env/bin/mp4box
fi

chmod 774 ~/termux-env/bin
chmod 775 ~/termux-env/bin/*

if [[ -L ~/bin && -d ~/bin ]]
then
	echo removing previous '~/bin'
	rm -rf ~/bin
fi

cwd2=$(pwd)
cd ~
ln -sv ./termux-env/bin ~/
cd $cwd2