#!/data/data/com.termux/files/usr/bin/bash

cwd=$(pwd)

for (( i=1; i<=5; i++ ))
do
	if [ $(dpkg-query -W -f='${Status}' git 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
		echo -e Git not install. Trying to install...
		apt install -y git;
	else
		break
	fi
done

if [ -d ~/termux-env ]; then
	echo removing old 'termux-env' dir
	rm -rf ~/termux-env
fi

cd ~/
git clone https://github.com/manishwg/termux-env.git
chmod 775 ~/termux-env/setenv
~/termux-env/setenv

cd $cwd     